### ISSUE TITLE
使用工具报错？

### ISSUE THREAD

**Issue by TomIsion** [TencentOpen/Fanvas#3]
@kenkozheng 

报错信息如下：

`fanvas3-min.js:14 Uncaught TypeError: Failed to execute 'createPattern' on 'CanvasRenderingContext2D': The provided value is not of type '(HTMLImageElement or HTMLVideoElement or HTMLCanvasElement or ImageBitmap)'`

按照项目中的Demo把`script`标签都放到了`head`标签中，同时写了定时器

查询错误之后发现可能是图片还没有加载结束就调用函数的原因，但是不知道该如何解决。求教

**Comment by kenkozheng** [comment]
请确认图片是否都成功加载了，控制台是否有关于图片加载的报错，或者是否图片格式有问题？
最好使用同源服务器进行测试。

**Comment by TomIsion** [comment]
说的方式都测试了下，但是貌似还是有同样问题

- [在线地址](https://tomision.github.io/)
- [github仓库](https://github.com/TomIsion/TomIsion.github.io)

图片比较多... 在线地址加载了很久，最后还是报之前的错误

然后本地也起过服务器，也是同样的报错。除了这个报错之外，没有其他错误

**Comment by kenkozheng** [comment]
嗯，跟踪了一下，有个图片缺失了。
如果你通过swf导出的swfData，那麻烦把swf发我kenkofox@qq.com看看。可能是swf格式比较特殊，有一些很老旧的图，不一定能覆盖到。
你也可以尝试把fla工程调整目标播放器版本，改为11以上，使用as3.0。这样导出的图片会使用新格式。

**Comment by TomIsion** [comment]
swf 文件已发

后面的内容看不太懂...
